source.. = src/
output.. = target/classes/
bin.includes = .,\
               META-INF/,\
               WEB-INF/,\
               lib/cxf-rt-databinding-xmlbeans.jar,\
               lib/cxf-rt-rs-extension-providers.jar,\
               lib/cxf-rt-bindings-object.jar,\
               lib/xmlbeans.jar
